export const allowedSubjects: string[] = [
  "Mathematics",
  "Algebra",
  "Geometry",
  "Trigonometry",
  "Calculus",
  "Statistics",
  "Physics",
  "Chemistry",
  "Biology",
  "Computer Science",
  "Information Technology",
  "Artificial Intelligence",
  "Machine Learning",
  "Data Science",
  "English",
  "Grammar",
  "Literature",
  "History",
  "World History",
  "Geography",
  "Civics",
  "Political Science",
  "Economics",
  "Psychology",
  "Sociology",
  "Environmental Science",
  "Earth Science",
  "Astronomy",
  "Philosophy",
  "Ethics",
  "Business Studies",
  "Accounting",
  "Finance",
  "Marketing",
  "Entrepreneurship",
  "Law",
  "Art",
  "Music",
  "Drama",
  "Health",
  "Physical Education",
  "General Knowledge",
  "Current Affairs",
  "Public Speaking",
  "Programming",
  "Web Development",
  "Cybersecurity",
];
